title: keter's blog
email: moshenwuji@live.com
description: The More I Learn, The Less I Know. 记录一些个人在程序开发学习中的一些历程 # this means to ignore newlines until "baseurl:"

baseurl: "" # the subpath of your site, e.g. /blog

avatar: facicon.ico
# twitter_username: 不用tt
github_username:  eterk


domain: eterk.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://eterk.github.io  # the base hostname and protocol for your site, e.g. http://example.com
# baseurl: /REPOSITORY-NAME/      # place folder name if the site is served in a subfolder

# Build settings
markdown: kramdown
theme: minima
repository: eterk/eterk.github.io
plugins:
  - jekyll-feed
  - jekyll-sitemap 

future: true
posts_showdrafts: true
posts_pagecount: 2
limit_posts: 50

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.

exclude:
  - Gemfile
  - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/